server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name drez-dev.id www.drez-dev.id _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}