server {
    listen 80;
    server_name drez-dev.id www.drez-dev.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name drez-dev.id www.drez-dev.id;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
